#pragma once

#include <stdbool.h>

#include "renderer/texture.h"

typedef enum MonitorFidelityTextureId {
    MONITOR_FIDELITY_NODE_SELECTED = 0,
    MONITOR_FIDELITY_CAM01_LABEL,
    MONITOR_FIDELITY_CAM02_LABEL,
    MONITOR_FIDELITY_CAM03_LABEL,
    MONITOR_FIDELITY_CAM04_LABEL,
    MONITOR_FIDELITY_CAM05_LABEL,
    MONITOR_FIDELITY_CAM06_LABEL,
    MONITOR_FIDELITY_CAM07_LABEL,
    MONITOR_FIDELITY_CAM08_LABEL,
    MONITOR_FIDELITY_CAM09_LABEL,
    MONITOR_FIDELITY_CAM10_LABEL,
    MONITOR_FIDELITY_MAINT_CURSOR,
    MONITOR_FIDELITY_MAINT_EXIT,
    MONITOR_FIDELITY_PROGRESS_0,
    MONITOR_FIDELITY_PROGRESS_1,
    MONITOR_FIDELITY_PROGRESS_2,
    MONITOR_FIDELITY_PROGRESS_3,
    MONITOR_FIDELITY_PROGRESS_4,
    MONITOR_FIDELITY_TEXTURE_COUNT
} MonitorFidelityTextureId;

bool monitor_fidelity_assets_init(void);
const TextureRle *monitor_fidelity_texture(MonitorFidelityTextureId id);
