#pragma once

#include <stdbool.h>

#include "renderer/texture.h"

typedef enum OriginalUiTextureId {
    ORIGINAL_UI_CAMERA_MAP_BASE = 0,
    ORIGINAL_UI_CAMERA_MAP_ALT,
    ORIGINAL_UI_VENT_MAP_BASE,
    ORIGINAL_UI_VENT_MAP_ALT,
    ORIGINAL_UI_TOOLBAR,
    ORIGINAL_UI_MAINT_AUDIO,
    ORIGINAL_UI_MAINT_AUDIO_ERROR,
    ORIGINAL_UI_MAINT_CAMERA,
    ORIGINAL_UI_MAINT_CAMERA_ERROR,
    ORIGINAL_UI_MAINT_VENT,
    ORIGINAL_UI_MAINT_VENT_ERROR,
    ORIGINAL_UI_MAINT_REBOOT_ALL,
    ORIGINAL_UI_MAINT_RESTART,
    ORIGINAL_UI_MAINT_MENU,
    ORIGINAL_UI_MUTE_CALL,
    ORIGINAL_UI_STATIC_0,
    ORIGINAL_UI_STATIC_1,
    ORIGINAL_UI_STATIC_2,
    ORIGINAL_UI_TRANSITION_0,
    ORIGINAL_UI_TRANSITION_1,
    ORIGINAL_UI_TRANSITION_2,
    ORIGINAL_UI_TRANSITION_3,
    ORIGINAL_UI_TRANSITION_4,
    ORIGINAL_UI_TRANSITION_5,
    ORIGINAL_UI_TRANSITION_6,
    ORIGINAL_UI_TEXTURE_COUNT
} OriginalUiTextureId;

bool original_ui_assets_init(void);
const TextureRle *original_ui_texture(OriginalUiTextureId id);
