#pragma once

#include <stdbool.h>

typedef enum AudioCue {
    AUDIO_CUE_VENT_QUIET_1 = 0,
    AUDIO_CUE_VENT_QUIET_2,
    AUDIO_CUE_VENT_CLOSER_1,
    AUDIO_CUE_VENT_LOUDER_2,
    AUDIO_CUE_ALARM,
    AUDIO_CUE_BREATHING,
    AUDIO_CUE_WAIT,
    AUDIO_CUE_STATIC,
    AUDIO_CUE_SCREAM,
    AUDIO_CUE_GARBLE,
    AUDIO_CUE_MASK,
    AUDIO_CUE_LURE_ECHO_1,
    AUDIO_CUE_LURE_ECHO_3B,
    AUDIO_CUE_LURE_ECHO_4B,
    AUDIO_CUE_PHONE_NIGHT_1,
    AUDIO_CUE_PHONE_NIGHT_2,
    AUDIO_CUE_PHONE_NIGHT_3,
    AUDIO_CUE_PHONE_NIGHT_4,
    AUDIO_CUE_PHONE_NIGHT_5,
    AUDIO_CUE_PHONE_NIGHT_6,
    AUDIO_CUE_SIX_AM,
    AUDIO_CUE_SELECT,
    AUDIO_CUE_END,
    AUDIO_CUE_CAMERA_OPEN,
    AUDIO_CUE_CAMERA_CLOSE,
    AUDIO_CUE_MAINTENANCE_CLOSE,
    AUDIO_CUE_MAINTENANCE_OPEN,
    AUDIO_CUE_GAME_OVER_AMBIENCE,
    AUDIO_CUE_TITLE_MUSIC,
    AUDIO_CUE_START_DAY,

    /* Optional full original sound-pack overrides. */
    AUDIO_CUE_OFFICE_FAN,
    AUDIO_CUE_RAIN_AMBIENCE,
    AUDIO_CUE_DANGER,
    AUDIO_CUE_REPAIR_SCANNER,
    AUDIO_CUE_REPAIR_DONE,
    AUDIO_CUE_MINIGAME_COLLECT,
    AUDIO_CUE_MINIGAME_FEED,
    AUDIO_CUE_MINIGAME_GLITCH,
    AUDIO_CUE_MINIGAME_CROWD,
    AUDIO_CUE_MINIGAME_CHIMES,
    AUDIO_CUE_MINIGAME_PARTY_FAVOR,
    AUDIO_CUE_ENDING_DESOLATE,
    AUDIO_CUE_MINIGAME_CRUSH,
    AUDIO_CUE_MINIGAME_BB_MUSIC,
    AUDIO_CUE_MINIGAME_MANGLE_MUSIC,
    AUDIO_CUE_MINIGAME_CHICA_MUSIC,
    AUDIO_CUE_MINIGAME_STAGE01_MUSIC,
    AUDIO_CUE_MINIGAME_SHADOW_MUSIC,
    AUDIO_CUE_MINIGAME_HAPPIEST_MUSIC,

    AUDIO_CUE_COUNT
} AudioCue;

bool audio_init(void);
void audio_shutdown(void);
void audio_play(AudioCue cue, float volume, bool loop);
void audio_stop(AudioCue cue);
void audio_stop_all(void);
void audio_restart(AudioCue cue, float volume, bool loop);
bool audio_is_available(void);
