#include "game/progress_save.h"

#include "main_v3_parts/main_00.inc"
#include "main_v3_parts/main_01.inc"
#include "main_v3_parts/main_phantom_visuals.inc"
#include "main_v3_parts/main_02.inc"
#include "main_v3_parts/main_03.inc"
#include "main_v3_parts/main_04.inc"
#include "main_v3_parts/main_05.inc"
#include "main_v3_parts/main_06.inc"
